config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/meditate', to: 'users#show'

  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/teacher_login', to: 'sessions#teacher_login'
  post '/teacher_login', to: 'sessions#connect'
  delete '/teacher_logout', to: 'sessions#destroy'

 post '/update_counter', to: 'sessions#update'

  post '/charge', to: 'charges#create'

  get '/begin', to: 'sessions#begin'
  get '/meditation', to: 'mantras#meditation'

  get '/add', to: 'teachers#new'



  post '/add_mantra', to: 'mantras#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :mantras
  resources :teachers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mantra.rb
class Mantra < ApplicationRecord
	validates :mantra, presence: true
	validates :phrase, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	before_save { self.yogi = yogi.downcase }
	validates :yogi, presence: true, length: {maximum: 50}

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }


    def Teacher.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :firstname, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :stripe_customer_id, presence: true
    validates :is_paid, presence: true

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def create
		@amount = 299

		 customer = Stripe::Customer.create({
		 	source: params[:stripeToken],
		 })
		 am = params[:mantra]
		 #pass this to the sessions helper 
		active_mantra(am)


		 @charge = Stripe::Charge.create({
		 	customer: customer.id, 
		 	amount: @amount, 
		 	description: "thatLovelyPracticeMeditation",
		 	currency: 'usd',
		 })

		 if !@charge.nil?
		 	redirect_to begin_path
		 end


		rescue Stripe::CardError => e
			flash[:error] = e.message
			redirect_to root_url
		end 



end

app/controllers/mantras_controller.rb
class MantrasController < ApplicationController
	before_action :end_guest_session, only: [:meditation]

	def index
		@mantra = Mantra.all
	end 


	def meditation
		@mantra = Mantra.all
	end


	def new
		@mantra = Mantra.new
	end

	def create
		@mantra = Mantra.new(mantra_params)
		if @mantra.save 
			flash[:success] = "Created the Mantra"
		else
			flash[:error] = "Unable to create mantra"
		end
	end

	def show
		@mantra = Mantra.find(params[:id])
	end

	def edit
		@edit_mantra = Mantra.find(params[:id])
	end

	def update
		@mantra = Mantra.find(params[:id])
		if @mantra.update(mantra_params)
			flash[:success] = "Updated the mantra"
		else 
			flash[:error] = "Unable to update"
		end
	end

	def destroy
	end

	private
	def mantra_params
		params.require(:mantra).permit(:mantra, :phrase)
	end

	def end_guest_session
			if  end_access < Time.now
				session[:status] = nil
				session[:counter] = nil
				 session[:expires_at] = nil 
				redirect_to root_url
			else
				if session_status == "starting"
					session[:status] = "in action"
				else
					session[:counter] = get_tracker
				end
			end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@mantras = Mantra.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		create_guest_session
		redirect_to meditation_path
	end

	def teacher_login
	end

	def connect
		yogi = Teacher.find_by(yogi: params[:session][:yogi].downcase)
		if yogi && yogi.authenticate(params[:session][:password])
			log_in yogi
			redirect_to yogi
		else
			flash.now[:error] = "Invalid LogIn"
			render 'teacher_login'
		end
	end

	def update
		session[:counter] = params[:session_update][:counter]
	end

	def destroy
		log_out
		redirect_to root_url
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	def show
		@yogi = Teacher.find(params[:id])
		@mantras = Mantra.all
	end

	def create
		@yogi = Teacher.new(yogi_params)
		if @yogi.save 
			flash[:success] = "YOGI added"
			
		else 
			flash[:error] = "YOGI not added."
			redirect_to @yogi
		end
	end

	def edit
		@yogi = Teacher.find(params[:id])
	end

	def update
		@yogi = Teacher.find(params[:id])
		if @yogi.update_attributes(yogi_params)
			flash[:success] = "Updated"
			redirect_to @yogi
		else
			flash[:error] = "Unable to Update"
		end
	end

	def destroy
		@yogi = Teacher.find(params[:id])
		@yogi.destroy
	end

	private
	 	def yogi_params
	 		params.require(:yogi).permit(:yogi, :password, :password_confirmation)
	 	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "thatLovelyPractice"
		if page_title.empty?
			base_title
		else
			page_title + ' - ' + base_title
		end
	end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/mantras_helper.rb
module MantrasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_guest_session
    session[:expires_at] = Time.now + 55 * 60
    session[:status] = "starting"
    session[:counter] = 0
  end

  #ends the user session after specified time
  def end_access
  	@time = session[:expires_at]
  end

  def current_session?
    @time.nil?
  end

  def time_split
  	sp = end_access.split("T")
  	sp[1].split(".")[0]
  end

  def active_mantra(mantra)
    session[:mantra_id] = mantra
  end

  def get_mantra 
    @m = session[:mantra_id]
  end

  def log_in(yogi)
    session[:teacher_id] = yogi.id
  end

  def current_yogi
    if session[:teacher_id]
      @teacher ||= Teacher.find_by(id: session[:teacher_id])
    end
  end

  def logged_in?
    !current_yogi.nil?
  end

  def log_out
    session.delete(:teacher_id)
    @teacher = nil
  end


  def get_tracker
    @begin = session[:counter]
  end

def set_current_counter ( curr_counter )
  session[:current_counter] = curr_counter
end

def get_current_counter
  @count = session[:current_counter]
end

def session_status
  @status = session[:status]
end



end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/_charges.html.erb
<%= form_tag charge_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
       <p style="color: #F2B383; font-weight: bold;">$2.99 <br>Per 30min Session</p>
    </label>
  </article>

  <%= hidden_field_tag :mantra, :id => 'mantra' %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Interactive Meditation"
          data-amount="299"
          data-locale="auto"></script>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
<p class="footer-opts"> Begin Interactive Meditation </p>
</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Atma" rel="stylesheet">
    <%= favicon_link_tag asset_path('yogaIcon.png') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
        <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/mantras/_add_mantra.html.erb
<%= form_for :mantra, url: add_mantra_path do |f| %>
<p><%= f.text_field :mantra, :required => true, :placeholder => "Mantra" %></p>
<p><%= f.text_field :phrase, :required => true, :placeholder => "Phrase" %></p>

<%= f.submit " Mantra" %>
<% end %>

app/views/mantras/_all_mantra.html.erb
<% if @mantras.count > 0 %>
<% @mantras.each do |m| %>
	<div class="mantra-display">
	<p class="mantra-words" id=<%= "#{m.id}"%>>.<%= m.mantra %> </p> 
	</div>

	<div class="mantra-tag" id=<%= "mantra_#{m.id}" %>><%= m.phrase %></div>
<% end %>
<% end %>

app/views/mantras/_list_all.html.erb
<% @mantras.each do |m| %>
	<p class="teacher-mantra"> Mantra : <%= m.mantra %> <br>Phrase : <%= m.phrase %> <%= link_to "Edit" , edit_mantra_path(m) , :class => 'teacher_bttns'%> <%= link_to 'Remove', mantra_path(m),
              method: :delete,
              data: { confirm: 'Are you sure?' }, :class => 'teacher_bttns' %> </p> 
<% end %>

app/views/mantras/meditation.html.erb
<div class="timer">
<p> YOUR SESSION EXPIRES AT 
<br> <%= time_split %> </p> 
</div>

<% @active_mantra = Mantra.find_by(id: get_mantra) %>

		<p id="set_counter" style="display:none;"><%= @counter = get_tracker %></p>
		<p class="mantra_counter" id="counter"> <%= @counter %> / 250  </p>
		<p class="mantra-instruct"> Relax. Click the mantra below to begin.Type the mantra as it appears. Do this (x250) for a successful session. </p>
		<%= render 'sessions/update_counter' %>

	<textarea class="mantras" id="bg_mantra" readonly><%= @active_mantra.phrase %></textarea>
	<textarea class="mantras" id="type_mantra"> </textarea>
	<p class="mini-mantra"> MANTRA <br> <%= @active_mantra.phrase %></p>


<div id="completed">
	<p> Congratulations. </p>
	<p> Your session is now complete</p>
	<%= link_to image_tag("yogaIcon.png"), root_url %>
</div>

app/views/pages/_attributes.html.erb
<h2> Pick an attribute </h2>

app/views/pages/home.html.erb
<% provide(:title, "Home")%>
<div id="home-content">

<% if session[:status].nil? %>

<div id="home-icon">
	<%= image_tag("yogaLogo-01.png", :id => 'home-logo' )%>
	<%= image_tag("yogaIcon.png", :id => "home-Icon") %>
</div> 

<div id="home-thoughts">
<p class="words"> we become what we think </p>
<p class="home-pg">The thoughts we habitually think about are the experiences that show up in our lives. These thoughts are who we become or the reality we experience.</p>
<p class="home-pg home-pg-two">The mind can be trained to default to good thoughts through repetition, auto-suggestion or mantra.
 Teaching the mind to respond with a good thought when prompted helps direct it towards a good life experience. 
 Conscious, transcendental meditation or auto-suggestion are the best way to direct the mind towards becoming the affirmations that inspire our best.</p>
</div>


<div id="home-login">
<div id="works">
	<p>?</p>
</div>

<div id="attributes">
		<h4> How It Works </h4>
		<p> 1. Start by selecting a mantra to attach to yourself. Remember that the definitions we attach to ourselves and the world around us are what become of us and what we experience. </p>
		<p> 2. Begin the 50 minute meditation session, where you will be prompted to write the idea 250 times. </p>
		 <p>3. Repeat as needed or until the mantra becomes part of your subconscious. </p>
</div>

<%= image_tag("icon-01.png", :id => "about") %>

<div id="med-tips">
	<h4> Repetition creates habit. We become our habits. </h4>
	<p> A wonderful life depends on the words we use to describe ourselves and our lives.</p>
	<p> It is created by good words. We become and experience what we say about ourselves and our lives.</p>
	<p> This app is a way to get into the habit of saying great things about ourselves, to become the best we are and experience the best lives we can live. </p>
</div>

	<div id="instructions">
		<p> Select A Mantra <span style="font-size: 0.45em; padding:0; margin: 0;"> to begin </span></p>

	</div>

		<div class="home-access" id="qa">
		<%= render 'mantras/all_mantra' %>
	</div>


	<div id="charge">
		<%= render 'charges/charges' %>
	</div>

	<div class="home-access" id="login">
		<%= render 'sessions/login' %>
	</div>


</div>



</div>

<footer>
<p class="footer-opts"> Conscious Meditation </p>
</footer>



<% else %>

	<div class="timer">
<p> Your Session Expires at </p>
<p> <%= time_split %> </p> 
</div>

	<%= image_tag("yogaIcon.png", :id => "home-Icon") %>
	 <%= link_to "Continue Your Session",  meditation_path, :id => "sesh" %>

<% end %>

app/views/teachers/_add_yogi.html.erb
<%= form_for :yogi, url: teachers_path do |f| %>
<p><%= f.text_field :yogi, :required => true , :placeholder => "yoginame"%></p>
<p><%= f.password_field :password, :required => true, :placeholder => "password" %></p>
<p><%= f.password_field :password_confirmation, :required => true, :placeholder => "password confirmation" %></p>
<%= f.submit "Hello Yogi" %>
<% end %>

app/views/teachers/_edit.html.erb
<p> Edit Profile </p>

app/views/teachers/new.html.erb
<%= form_for :yogi, url: teachers_path do |f| %>
<p><%= f.text_field :yogi, :required => true , :placeholder => "yoginame"%></p>
<p><%= f.password_field :password, :required => true, :placeholder => "password" %></p>
<p><%= f.password_field :password_confirmation, :required => true, :placeholder => "password confirmation" %></p>
<%= f.submit "Hello Yogi" %>
<% end %>

app/views/teachers/show.html.erb
<% provide(:title, "Yogi Page")%>
<div id="yogi_page">
	<div class="teacher-content-mantras">
		<p style="color: #5C99B9; font-size:2.5em;"> all mantras </p>
		<p> <%= render 'mantras/list_all' %> </p>
	</div>

	<div class="teacher-content">
		<p style="color: #5C99B9; font-size:1.5em;">> Add Mantra </p>
		<p> <%= render 'mantras/add_mantra' %> </p>
	</div>

	<div class="teacher-content add-teacher">
		<p style="color: #5C99B9; font-size:1.5em;">> Add Teacher </p>
		<p> <%= render 'teachers/add_yogi' %> </p>
	</div>

<%= link_to "Log out", logout_path, method: :delete, :class=> 'teacher_bttns logout-teacher' %>
</div>

app/views/users/_signup.html.erb
<p> Coming Soon </p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>